### ISSUE TITLE
il flavour "tile" non rispetta il bounding box sul livello più basso di zoom

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#131]
Con un flavour tipo:

```
  tile:
     zoom_min: 6
     zoom_max: 7
     lat_min: 35.0
     lat_max: 48.0
     lon_min: 5.0
     lon_max: 20.0
```
viene rispettato il bounding box per il livello 7 ma il livello 6 copre un'area più larga

Il `products.json` segna lo stesso bounding box del tile
