### ISSUE TITLE
errori di validazione su plot con simboli (macro msymb)

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#179]
Sto cercando di tradurre in ricetta arkimaps un plot con simboli (allego grib di test, script python di esempio e output png risultante).

La ricetta test che avevo preparato è una cosa del genere:
```
---
description: Precipitation types
inputs:
 precitype:
   - model: ifs
     arkimet: product:GRIB2,98,0,1,19,,
     eccodes: shortName is "ptype"
recipe:
 - step: add_basemap
 - step: add_coastlines_bg
 - step: add_grib
   grib: precitype
   params:
     grib_scaling_factor: 1
 - step: add_symbols
   params:
     symbol_type: "marker"
     symbol_table_mode: "on"
     symbol_min_table: [1,3,5,6,8,9,12]
     symbol_max_table: [2,4,6,7,9,10,13]
     symbol_marker_table: [18,18,18,18,18,18]
     symbol_colour_table: ["GREEN","RED","BLUE","YELLOW","TURQUOISE","YELLOWISH_ORANGE","ochre"]
     symbol_height_table: [0.6,0.6,0.6,0.6,0.6,0.6]
     legend: "on"
     legend_title: on
     legend_text_colour: black
     legend_text_font_size: 0.4
     legend_title_font_size: 0.5
     legend_title_test: "Precipitation types"
     legend_automatic_position: right
 - step: add_coastlines_fg
 - step: add_grid
 - step: add_boundaries
 - step: add_user_boundaries
 - step: add_geopoints
```

ma genera una serie di errori di validazione:
```
pydantic.error_wrappers.ValidationError: 6 validation errors for AddSymbolsSpec
params -> symbol_colour_table
  extra fields not permitted (type=value_error.extra)
params -> symbol_height_table
  extra fields not permitted (type=value_error.extra)
params -> symbol_marker_table
  extra fields not permitted (type=value_error.extra)
params -> symbol_max_table
  extra fields not permitted (type=value_error.extra)
params -> symbol_min_table
  extra fields not permitted (type=value_error.extra)
params -> symbol_table_mode
  extra fields not permitted (type=value_error.extra)
```

i parametri però sono previsti dalla macro mysmb (https://confluence.ecmwf.int/display/MAGP/Symbol).

Ipotizzo vadano aggiunti come defaults a `steps.py` ma non so se ci siano altri modi.
