### ISSUE TITLE
Rendering: total snow fall a 1h, 3h, 6h, 12h e 24h

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#24]
**[:scroll: Documento di analisi nel wiki :scroll:](https://github.com/ARPA-SIMC/arkimaps/wiki/issue24)**

sigla: **sf** associata al periodo tipo **sf1h** **sf3h**...

variabili necessarie:
`GRIB1,98,128,144` (IFS-ECMWF)
`GRIB1,,2,78` + `GRIB1,80,2,79` (COSMO)

Preprocessing:
- solo per COSMO: sommare i due parametri (sono snow fall convettiva e large-scale)
- riportare preci ECMWF in mm come da #17
- cumulazione come da #17

**Comment by spanezz** [comment]
Sarei tentato di taggare questo issue multiprod e riassegnarmelo, visto che c'è da sommare due input diversi. C'è un motivo per cui non è al momento assegnato a me?

**Comment by brancomat** [comment]
Sì, credo stessi aspettando risposta sul discorso della somma convettiva+large scale per conferma, ma Davide ha già confermato qui: https://github.com/ARPA-SIMC/arkimaps/issues/17#issuecomment-762144953

tolgo label e te l'assegno

**Comment by dcesari** [comment]
Scusate, mi era sfuggita la domanda, comunque si, come detto in altro commento, devo sommare large scale e convettiva, a patto che la convettiva esista in archivio, non so se si può etichettare la sua mancanza come warning e non come errore. Il conto lo fa anche libsim con variabile in uscita B13205, ma chiaramente fallisce nel caso di mancanza della frazione convettiva come in cosmo 2.2.

**Comment by spanezz** [comment]
Mi servirebbe sintetizzare i vari ragionamenti in una strategia implementativa.

Provo ad abbozzare partendo dalla mia nebulosa incomprensione: magari editate questo commento coi pezzi che mancano:

## COSMO

Se è presente la snow-fall convettiva, sommarla alla large-scale usando libsim. Altrimenti usare direttamente la large scale.

**TODO**: comando di libsim

## ECMWF

Decumulare la total snow con libsim (#17).

**TODO**: comando di libsim

## Entrambi

Ri-cumulare con libsim? Non avevamo appena decumulato?

**Comment by spanezz** [comment]
> la tabella libsim di cui sopra deve essere estesa con i corrispondenti parametri grib2 che si spera esistano nelle tabelle standard WMO
Questo è bloccante per l'implementazione di questo ticket, giusto?

**Comment by dcesari** [comment]
Al momento non è bloccante. Lo sarà quando utilizzeremo dati in grib2. Al momento in grib2 abbiamo solo il cosmo 2I ensemble, di cui non credo andremo a visualizzare questi dati, tra ~6 mesi avremo le previsioni di ICON che sono solo in grib2.

L'estensione è un lavoro minuzioso ma non difficile, apro comunque issue in libsim per tenerne traccia.

**Comment by dcesari** [comment]
> Per Cosmo ho aggiornato. Per ECMWF avete qualche query dai nostri archivi sottomano? Se non ricordo male i dati di ECMWF sono già "decumulati" su intervalli prestabiliti, per cui è forse a causa di questo che è stato inserito l'ultimo punto "ricumulare", cioè nel caso in cui l'intervallo desiderato sia un multiplo dell'intervallo disponibile in archivio.

Ho verificato che, a differenza di quanto avevo ipotizzato, il parametro ECMWF `product:GRIB1,98,128,144` è anch'esso cumulato sempre a partire dall'istante zero, per cui si può trattare come i dati di Cosmo e non dovrebbe esserci necessità di "ricumulare" nel tempo.

**Comment by spanezz** [comment]
> Ho verificato che, a differenza di quanto avevo ipotizzato, il parametro ECMWF `product:GRIB1,98,128,144` è anch'esso cumulato sempre a partire dall'istante zero, per cui si può trattare come i dati di Cosmo e non dovrebbe esserci necessità di "ricumulare" nel tempo.

Puoi aggiornare https://github.com/ARPA-SIMC/arkimaps/wiki/issue24 di conseguenza? Cosí una volta che converge parto con l'implementazione

**Comment by brancomat** [comment]
@spanezz il documento mi pare completo (in sostanza per IFS usi le stesse opzioni che useresti per COSMO nella decumulazione mentre non c'è lo step di sommare large scale e convettiva) , ti servono altre info?

**Comment by spanezz** [comment]
Nel caso di COSMO, immagino che uno di `product:GRIB1,,2,78` e `product:GRIB1,80,2,79` sia large scale e l'altro convettiva.

Per dare un nome sensato agli input intermedi, quale dei due è large scale e quale convettiva?

Lato eccodes, come li distinguo invece?

**Comment by spanezz** [comment]
Per eccodes, direi `snow_gsp` e `snow_con`. andando all'indietro, direi che `product:GRIB1,,2,78` sia convettiva e `product:GRIB1,80,2,79` sia large_scale.

Vado avanti con queste assunzioni salvo input vostro

**Comment by brancomat** [comment]
Confermo:

Convective snow
GRIB1,,2,78
shortName: snow_con

Large scale snow
GRIB1,,2,79
shortName: snow_gsp

**Comment by spanezz** [comment]
All'istante `+0` di COSMO, quella che per eccodes normalmente è `snow_con` diventa `snoc`, e quella che per eccodes normalmente è `snow_gsp` diventa `lssf`.

Quale sarebbe la differenza?

Posso mettere impunemente questi filtri per eccodes?
```yaml
 snow_con:                           
   - model: cosmo
     arkimet: product:GRIB1,,2,78
     eccodes: shortName is "snow_con" or shortName is "snoc"
 snow_gsp:  
   - model: cosmo
     arkimet: product:GRIB1,80,2,79
     eccodes: shortName is "snow_gsp" or shortName is "lssf"
```

**Comment by spanezz** [comment]
Bozza di ricetta. Mi confermate i FIXME per il caso in cui manchi la convettiva?
```yaml
---
description: Total snow fall 3h
inputs:
 sf:
   - model: ifs
     arkimet: product:GRIB1,98,128,144
     eccodes: shortName is "sf"
 snow_con:
     # FIXME: this is optional. If it is not present, it should be ignored/skipped
   - model: cosmo
     arkimet: product:GRIB1,,2,78
     eccodes: shortName is "snow_con" or shortName is "snoc"
 snow_gsp:
   - model: cosmo
     arkimet: product:GRIB1,80,2,79
     eccodes: shortName is "snow_gsp" or shortName is "lssf"
 snow_sum:
     # FIXME: if snow_con is missing, this step should be skipped and snow_gsp
     # should be used instead of its output
   - model: cosmo
     type: vg6d_transform
     args: ["--output-variable-list=B13205"]
     inputs: [snow_con, snow_gsp]
 snowdec3h:
   - model: cosmo
     type: decumulate
     step: 3
     inputs: snow_sum
   - model: ifs
     type: decumulate
     step: 3
     inputs: sf
recipe:
 - step: add_basemap
 - step: add_coastlines_bg
 - step: add_grib
   grib: snowdec3h
 - step: add_contour
   params:
    contour: "off"
    contour_highlight: "off"
    contour_hilo: "off"
    contour_label: "off"
    contour_level_selection_type: "level_list"
    contour_shade: "on"
    contour_shade_colour_method: "list"
    contour_shade_method: "area_fill"
    contour_shade_min_level: 0.5
    contour_level_list: [0.5, 1.0 ,2.0, 5.0, 10.0 ,20.0, 30.0, 50.0, 70.0, 100.0, 150.0, 200.0]
    contour_shade_colour_list: [ "rgb( 0.686,1.000,1.000)", "rgb( 0.000,1.000,1.000)",
            "rgb( 0.447,0.639,1.000)", "rgb( 0.000,0.498,1.000)",
            "rgb( 0.145,0.000,1.000)", "rgb( 0.145,0.435,0.435)",
            "rgb( 1.000,1.000,0.000)", "rgb( 1.000,0.498,0.000)",
            "rgb( 1.000,0.000,0.000)", "rgb(1.000,0.000,1.000)",
            "rgb(0.615,0.403,0.937)" ]
    legend: on
# TODO: from this point on it's copied from tp1h: is this valid also in this case?
    legend_display_type: continuous
    legend_title: on
    legend_text_colour: black
    legend_text_font_size: 0.4
    legend_title_font_size: 0.5
    legend_title_text: "Total snow fall [mm]"
    legend_automatic_position: right
 - step: add_coastlines_fg
 - step: add_grid
 - step: add_boundaries
 - step: add_user_boundaries
 - step: add_geopoints
 - step: add_symbols
```
