### ISSUE TITLE
Refactoring gestione degli input

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimaps#41]
Le opzioni che ci sono per gli input sono:

 - input alternativi per lo stesso dato, con gestioni diverse a seconda del modello che le ha generate (per esempio, un modello va scalato per un valore, l'altro per un altro, o un modello va scalato e l'altro no)
 - regole di filtraggio diverse per akimet e eccodes

Dove ora c'è:
```
inputs:
 tcc: product:GRIB1,,2,71 or GRIB1,98,128,164
inputs_grib:
 tcc: shortName is "tcc"
```

Si può cambiare con:
```
inputs:
 tcc:
  - arkimet: product:GRIB1,,2,71
    eccodes: shortName is "tcc" and qualcosa
    mgrib:
        grib_automatic_scaling: off
        grib_scaling_factor: 0.01
  - arkimet: product:GRIB1,98,128,164
    eccodes: shortName is "tcc" and qualcosaltro
```

Rendendo quindi 'inputs' un dict che mappa ogni nome a una lista di dict che contengono definizioni alternative per lo stesso input, ognuna con opzioni diverse, e lui prende la prima per la quale trova i dati e ignora le altre.

Questo lascia spazio per definire preprocessatori diversi a seconda del tipo di input
