### ISSUE TITLE
document-recipes non rappresenta correttamente gli input

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#79]
nella recipe [tp_inputs.yaml](https://github.com/ARPA-SIMC/arkimaps/blob/master/recipes/tp_inputs.yaml) usata dai vari `tp${HH}h.yaml` sono definiti due modelli:
```
 tp:
   - model: cosmo
     arkimet: product:GRIB1,,2,61
     eccodes: shortName is "tp"
   - model: ifs
     arkimet: product:GRIB1,98,128,228
     eccodes: shortName is "tp"
```

nella documentazione autogenerata con `document-recipes` però viene proposto come codice di `ifs` quello di `cosmo`, vedi ad es.:
https://github.com/ARPA-SIMC/arkimaps/blob/master/recipes/tp1h.md
```
tp:
Model cosmo:
Arkimet matcher: product:GRIB1,,2,61
grib_filter matcher: shortName is "tp"
Model ifs:
Arkimet matcher: product:GRIB1,,2,61
grib_filter matcher: shortName is "tp"
```
