### ISSUE TITLE
Gestione dell'input: usare direttamente i metadati arkimet invece di pattern

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimaps#9]
Attualmente, lo smistatore divide l'input in vari file e il renderizzatore associa un alias ad ogni pattern, e.g.

```yaml
name: Temperatura a 2 metri
inputs:
    msl: "+*/t-*.grib"
```

È un passaggio che potrebbe essere eliminato usando direttamente i valori dei metadati di arkimet, visto che si deve comunque passare per un `arki-scan` o `arki-query`.
