### ISSUE TITLE
Rendering: jet stream (corrente a getto)

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimaps#93]
Variabili:

già definite: `z250`, `uv250`
da fare: `wmax250`
vento massimo calcolato dalle componenti u e v come radice quadrata di (u² + v²)
versione fortran: `sqrt(ucomp(i)**2+vcomp(i)**2)`

(in questo caso serve a 250hPa ma ovviamente la formula sarebbe da implementare in generale)

Contouring (yaml completo):
```
---
description: Wind, maximum wind gust speed  and Geopotential at 250hPa
recipe:
 - step: add_basemap
 - step: add_coastlines_bg
 - step: add_grib
   grib: wmax250
 - step: add_contour
   params:
    contour: off
    contour_shade: on
    contour_level_selection_type: list
    contour_shade_colour_method: list
    contour_shade_method: area_fill
    contour_shade_colour_list: ["yellow", "beige", "gold", "khaki"]
    contour_level_list: [35.0, 45.0, 55.0, 65.0, 150.0]
    contour_highlight: off
    contour_hilo: off
    legend: on
    legend_title: on
    legend_title_text: 'Maximum wind gust speed [m/s]'
    legend_display_type: continuous
    legend_automatic_position: right
 - step: add_grib
   grib: z250
 - step: add_contour
   params:
    contour_shade: off
    contour: on
    contour_level_selection_type: interval
    contour_interval: 4
    contour_line_colour: black
    contour_line_thickness: 3
    contour_highlight: off
    contour_label: on
    contour_label_height: 0.6
    contour_label_frequency: 2
    contour_label_blanking: on
    contour_label_colour: navy
    legend: off
 - step: add_grib
   grib: uv250
 - step: add_wind
   params:
     wind_field_type: flags
     wind_flag_colour: blue
     #wind_flag_length: 0.8
     wind_flag_origin_marker: off
     wind_flag_cross_boundary: on
     wind_thinning_factor: 4
 - step: add_coastlines_fg
 - step: add_grid
 - step: add_boundaries
 - step: add_user_boundaries
 - step: add_geopoints
 - step: add_symbols
```
